### ISSUE TITLE
Workflow chapter - spatialLIBD

### ISSUE THREAD

**Issue by lmweber** [lmweber/OSTA-book#3]
Add a new workflow chapter using `spatialLIBD` dataset/package.

This should include a description of the dataset, followed by a complete workflow, starting with loading the data as a `SpatialExperiment` and followed by the individual analysis steps. The structure should be adapted as necessary, depending on the specific dataset and platform. Documentation does not need to be extensive, since the analysis steps are described in more detail in previous chapters - but should be enough that readers can follow along and see how the steps connect.

**Comment by lcolladotor** [comment]
https://github.com/lmweber/OSTA-book/pull/11 resolves this
